image: docker:latest

stages:
  - publish

before_script:
  - apk add --update --no-cache make
  - make dist
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json

deploy_production:
  image: google/cloud-sdk:alpine
  stage: publish
  # only:
  #   - master
  script:
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gsutil -m cp -r dist/* gs://blog.verygoodsoftwarenotvirus.ru/

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
