apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: blog
  name: blog-config
data:
  nginx.conf: |
    server {
      listen       8080;
      server_name  localhost;

      location / {
          root   /blog;
          index  index.html;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blog
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: blog-config
      containers:
        - image: verygoodsoftwarenotvirus/blog:latest
          imagePullPolicy: Always
          name: blog
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
          resources:
            requests:
              memory: '64Mi'
              cpu: '128m'
            limits:
              memory: '128Mi'
              cpu: '250m'
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
  annotations:
    external-dns.alpha.kubernetes.io/hostname: blog.verygoodsoftwarenotvirus.ru
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    external-dns.alpha.kubernetes.io/ttl: '120' #optional
spec:
  selector:
    app: blog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: blog
---

