on:
  pull_request:
    paths:
      - content/**
      - static/**
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.1'

      - name: Build
        run: hugo --destination dist/ --minify --config=config.toml

